[package]
authors = ["Blas Rodriguez Irizar <rodrigblas@gmail.com>"]
edition = "2018"
name = "matecito"
version = "0.1.0"
[dependencies]
twox-hash = "*"
parking_lot = "0.11.0"
matecito-dll = "0.1.0"

[dependencies.serde]
features = ["derive"]
version = "1.0.115"
